import Head from 'next/head'
import Image from 'next/image'
import Button1 from '../component/Button/Button'
import CardItem from '../component/cardItem/CardItem'
import NavBar from '../component/footer/navBar/NavBar'
import HomePageHeader from '../component/homePageSection/homePageSection/HomePageHeader'
import HomePageSection from '../component/homePageSection/homePageSection/HomePageSection'
import HomePageSection2 from '../component/homePageSection/homePageSection/HomePageSection2'
import HomeShipping from '../component/homeShipping/HomeShipping'
import BuyingHypeindustry from '../component/hypeindustry/buyingHypeindusrty/BuyingHypeindustry'
import RealFooter from '../component/realFooter/RealFooter'
import SellingNavbar from '../component/sellingNavbar/SellingNavbar'
import SellQuestion from '../component/sellQuestion/SellQuestion'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

            
      <NavBar></NavBar>
         
        <HomePageHeader src="Vector.png" heading='New marketplace that allows you to buy in bulk'  paragrapg='Hypeindustry is a one-of-a-kind Platform+Marketplace offering Bulk/Wholesale goods from 
        Stores, Boutiques,Wholesalers & Resellers for the Footwear,Apparel & Accessory industry.'></HomePageHeader> 
        
        
       <HomePageSection src='Frame 1 (2).png' heading='Why HypeIndustry and what is it' paragrapg='Hypeindustry is a one-of-a-kind Platform + Marketplace offering Bulk/Wholesale goods from Stores, Boutiques, Wholesalers & Resellers for the Footwear, Apparel & Accessory industry! Basically a
        new marketplace that allows you to buy in bulk (only) footwear, apparel etc...'></HomePageSection>
   
   <HomePageSection2 src='factory-workshop-interior-machines-glass-production-background 2.png' paragraph='Buy cheaper because of the bulk volume discount and resell worldwide to make a small margin
    and keep the volume and recurrence active! The key to make your money fast .'></HomePageSection2>



  <SellingNavbar></SellingNavbar>
    <SellQuestion></SellQuestion>
    <BuyingHypeindustry></BuyingHypeindustry>
    <HomeShipping className={'left'} src={'Group.png'} heading={'Shipping for buyers'} paragraph={'All of our items are being shipped from several warehouses/stores in the USA and worldwide, and usually ships within 24 H to 5 business days depending on the seller’s shipping time.'}></HomeShipping>
     <HomeShipping className={'right'} src={'Package.png'} heading='Shipping for sellers' paragraph='Once you have approved the purchase, you can request for your labels by email at: shipping@hypeindustry.com! Make sure to include: 
          Buyer’s details...'></HomeShipping>
    
    
  

     <div className='home-footer'>
    <RealFooter></RealFooter>
     </div>
    
    </div>
    
  )
}
